### ISSUE TITLE
Pretrained weights and documentation for adding a new robot

### ISSUE THREAD

**Issue by apirrone** [nico-bohlinger/one_policy_to_run_them_all#1]
Hello ! Great stuff, congrats ! 

Do you provide pretrained weights somewhere ? I could not find it.

Also, are there instructions somewhere on how to add a new robot to try it with the general policy ? 

Thanks !

**Comment by nico-bohlinger** [comment]
Hey, those a great points!

I added pre-trained model in the experiments folder that you can simply use with the test.sh script.
And I added a section in the README on how to add a new robot and which parts might need to be adjusted.

**Comment by apirrone** [comment]
Wow thanks for the very quick answer and solution, amazing !
