### ISSUE TITLE
Issue encountered during installation

### ISSUE THREAD

**Issue by Ericongic** [nico-bohlinger/one_policy_to_run_them_all#2]
## Description of the issue
When following the installation process provided in the README and running `pip install -e .`, I encountered the following error:

```
ERROR: Ignored the following yanked versions: 0.4.32

ERROR: Ignored the following versions that require a different python version: 0.0.322773188 Requires-Python >=3.6, <3.10; 0.0.355168290 Requires-Python >=3.6, <3.10; 0.0.364896371 Requires-Python >=3.6, <3.10; 0.0.403778684 Requires-Python >=3.7, <3.10; 0.0.423341706 Requires-Python >=3.7, <3.10; 0.0.425341097 Requires-Python >=3.7, <3.10; 1.0.0 Requires-Python >=3.7, <=3.10; 1.0.1 Requires-Python >=3.7, <=3.10; 1.0.2 Requires-Python >=3.7, <=3.10

ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.25+cuda12.cudnn89 (from one-policy-to-run-them-all) (from versions: 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.33, 0.4.34)

ERROR: No matching distribution found for jaxlib==0.4.25+cuda12.cudnn89
```

## Steps Taken:

Verified that my Python version is 3.11.4, which is compatible with the requirements in the README.
My CUDA version is 11.8, and it is installed correctly.
Other dependencies were installed without issues following the instructions in the README.

Could you provide any suggestions or recommended steps to resolve this issue and install the correct dependencies?

Thank you very much. All the best!

**Comment by nico-bohlinger** [comment]
Both issues that you encountered should be fixed with the installation instructions in the newest commit.
Essentially make sure that RL-X is installed first and that the jaxlib and torch versions are matching the ones in the requirements.txt by installing:
```
pip install "torch==2.2.1" --index-url https://download.pytorch.org/whl/cu118 --upgrade
pip install -U "jax[cuda12_pip]==0.4.25" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by zzzzzzxm** [comment]
conda install pytorch==2.2.1 torchvision==0.17.1 torchaudio==2.2.1 pytorch-cuda=11.8 -c pytorch -c nvidia
use this command from official pytorch website before pip install -e . is useful.

**Comment by zzzzzzxm** [comment]
> Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> 
> × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [3 lines of output] error in one_policy_to_run_them_all setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected package name at the start of dependency specifier -e git+ssh://[git@github.com](mailto:git@github.com)/nico-bohlinger/RL-X.git@5119c303a09102272352f7770b2d85c46bfe44e2#egg=rl_x ^ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

And for this, since RL-X is installed before pip install -e . as in README, this line in requirement.txt can be annotated to avoid this error.

**Comment by nico-bohlinger** [comment]
> > Preparing metadata (setup.py) ... error error: subprocess-exited-with-error
> > × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [3 lines of output] error in one_policy_to_run_them_all setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected package name at the start of dependency specifier -e git+ssh://[git@github.com](mailto:git@github.com)/nico-bohlinger/RL-X.git@5119c303a09102272352f7770b2d85c46bfe44e2#egg=rl_x ^ [end of output]
> > note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> > × Encountered error while generating package metadata. ╰─> See above for output.
> > note: This is an issue with the package mentioned above, not pip. hint: See above for details.
> 
> And for this, since RL-X is installed before pip install -e . as in README, this line in requirement.txt can be annotated to avoid this error.

Exactly, this is why I now removed it from the requirement.txt
