### ISSUE TITLE
Missing multi_render.txt

### ISSUE THREAD

**Issue by mattia-risiglione** [nico-bohlinger/one_policy_to_run_them_all#3]
Hi, 

 I cannot find the  multi_render.txt file, mentioned in the readme to switch the robot. Where is that?

Thanks

**Comment by mattia-risiglione** [comment]
Same goes for the commands.txt file

**Comment by nico-bohlinger** [comment]
Hey!

Those files are in the .gitignore so potentially frequent changes are not tracked by git but I forgot to add them to the repo before that.
With the last commit you can find them now in the experiments folder.
