### ISSUE TITLE
Robot Fails to Move

### ISSUE THREAD

**Issue by andvg3** [nico-bohlinger/one_policy_to_run_them_all#8]
Hi authors,

I'm testing with a different robot (not the `unitree_a1`) by modifying the `multi_render.txt` file. However, the new robot does not appear to move in this setup. I've attached a screenshot below for reference.

Additionally, here is the log:

> .../one_policy_to_run_them_all/environments/unitree_a1/reward_functions/rudin_own_var.py:175: RuntimeWarning: divide by zero encountered in divide
>   tracking_performance_percentage = max(np.mean(1 - (np.abs(current_global_velocities - desired_global_velocities) / np.abs(desired_global_velocities))), 0.0)

Could you help me resolve this issue? Thanks!

![image](https://github.com/user-attachments/assets/afe0d134-41a0-4276-8d2b-a6729ee58fbf)

**Comment by nico-bohlinger** [comment]
Hey!
Can you confirm that this also happens on the newest commit: [d9d166c](https://github.com/nico-bohlinger/one_policy_to_run_them_all/commit/d9d166c348496c9665dd3ebabc20efb6d8077161)?
I pushed this commit related to that issue two days ago

**Comment by andvg3** [comment]
Thanks, the newest commit has resolved the issue.
